# Generated by Django 2.2.1 on 2019-12-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
